import { NextResponse } from 'next/server';
import dbConnect from '@/lib/mongodb';
import Skill, { ISkill } from '@/models/Skill';
import { getSkills } from '@/lib/skills';

// Remove the dummy data store
// let skills = [
//   { id: '1', name: 'JavaScript', proficiency: 'Advanced' },
//   { id: '2', name: 'React', proficiency: 'Intermediate' },
// ];

export async function GET(request: Request) {
  try {
    const skills = await getSkills();
    return NextResponse.json(skills);
  } catch (error) {
    console.error('Error fetching skills:', error);
    const errorMessage = error instanceof Error ? error.message : 'An unknown error occurred';
    return NextResponse.json({ message: 'Error fetching skills', error: errorMessage }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    await dbConnect();
    const newSkillData = await request.json();
    if (!newSkillData.name || !newSkillData.proficiency || !newSkillData.category) {
      return NextResponse.json({ message: 'Missing name, proficiency, or category' }, { status: 400 });
    }
    // The id will be automatically generated by MongoDB
    const skill = new Skill(newSkillData);
    await skill.save();
    return NextResponse.json(skill, { status: 201 });
  } catch (error) {
    console.error('Error creating skill:', error);
    // Check for duplicate key error (if you add unique indexes)
    // if (error.code === 11000) {
    //   return NextResponse.json({ message: 'Skill already exists' }, { status: 409 });
    // }
    return NextResponse.json({ message: 'Error creating skill', error }, { status: 500 });
  }
}
